BUG: Fix `utils.error(message)` EmitLoopError and AttributeError
The original code triggered an error, saying:

> EmitLoopError:
>
> While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in a callback:
>
>  AttributeError: 'QMessageBox' object has no attribute 'source'

Fixed by calling QMessageBox.critical, and returning nothing, instead of returning the created instance of QMessageBox.